name: Test Sample Applications

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-samples:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.0', '3.1', '3.2']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Make scripts executable
      run: |
        chmod +x setup.sh
        chmod +x test_all.sh

    - name: Set up sample applications
      run: ./setup.sh

    - name: Test all samples
      run: ./test_all.sh

  docker-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Test Hello World Docker setup
      run: |
        cd samples/helloworld-agent
        docker-compose up --build --abort-on-container-exit